// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RealAirplaneTag;
//
//    var map = Map.FromJson(jsonString);

namespace RealAirplaneTag
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    public partial class Map
    {
        [JsonProperty("arrivals")]
        public string[] Arrivals { get; set; }

        [JsonProperty("departures")]
        public string[] Departures { get; set; }
    }

    public partial class Map
    {
        public static Dictionary<string, Map> FromJson(string json) => JsonConvert.DeserializeObject<Dictionary<string, Map>>(json, RealAirplaneTag.Converter.Settings);
    }





}